apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-news-app

spec: 
  replicas: 5
  selector: 
    matchLabels:
      app: ibm-news-app
  template:
    metadata:
      labels:
        app: ibm-news-app
    spec: 
      containers:
        - name: ibm-ibm-news-app
          image: ibm-ibm-news-app
          imagePullPolicy:  Never
          ports :
            - containerPort: 5000
              protocol: TCP
